// Code generated by "stringer -type=ExitCode exitcode.go"; DO NOT EDIT.

package mainframe

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ok-0]
	_ = x[Failure-1]
	_ = x[Quit-2]
}

const _ExitCode_name = "OkFailureQuit"

var _ExitCode_index = [...]uint8{0, 2, 9, 13}

func (i ExitCode) String() string {
	if i < 0 || i >= ExitCode(len(_ExitCode_index)-1) {
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExitCode_name[_ExitCode_index[i]:_ExitCode_index[i+1]]
}
